Feat: teacher domain
dev-sect/ScheduleDevelopmentKit-backend pull request #14
Opened 2021-11-23 08:50 UTC by Bibletoon

Closes #3 
Closes #2 
Так же посмотрел, и метод для получения преподавателя по Id выглядит законченным, так что думаю #4 можно закрывать

2021-11-23 12:42 UTC, s4xack requested changes

2021-11-23 12:42 UTC, s4xack commented on src/ScheduleDevelopmentKit.DataAccess/EntityConfigurations/EmailConfiguration.cs
> +    public class EmailConfiguration : IEntityTypeConfiguration<Email>
Ты конечно конфигурации запилил, но не заинжектил в контекст.
Вообще предлагаю конфигурации ВО не выносить отдельно, а делать внутри конфигурации Entity, на уровне данных, это все же цельный кусок, который должен конфигаться разом

2021-11-23 12:42 UTC, s4xack commented on src/ScheduleDevelopmentKit.Modules.Core/Teachers/Commands/CreateTeacher.cs
>                  RuleFor(x => x.PhoneNumber).Length(12).Must(x => x.StartsWith("+7"));
Валидация не совпадает с валдидацией в ВО, в итоге пользователь получит 500, вместо 400, если передаст `+7aabbccddee`.

Еще есть мысль подумать над тем как бы организовать реюз валидаций из ВО в валидаторах хэндлеров (пока что хз, стоит ли, ибо это добавит ненужных зависимостей)

2021-11-23 14:15 UTC, Bibletoon commented on src/ScheduleDevelopmentKit.Modules.Core/Teachers/Commands/CreateTeacher.cs
>                  RuleFor(x => x.PhoneNumber).Length(12).Must(x => x.StartsWith("+7"));
Вообще она совпадает (и там, и там +7 и 10 случайных символов), но проблема в том, что она хреновая (должны быть не символы, а только цифры)

По поводу реюза согласен, так как подобных проблем позже может возникнуть много

2021-11-23 14:17 UTC, Bibletoon commented on src/ScheduleDevelopmentKit.DataAccess/EntityConfigurations/EmailConfiguration.cs
> +    public class EmailConfiguration : IEntityTypeConfiguration<Email>
В связи с этим такой вопрос возник: ValueObject подразумевает, что он используется только внутри определённого класса. Просто если будет условный Student, у которого тоже есть PersonName, будет неудобно искать где он конфигурируется. Или стоит выносить конфиг по мере использования: заюзали в другом классе и вместе с эти вынесли конфиг VO?

2021-11-26 19:50 UTC, s4xack approved these changes

2021-11-26 23:07 UTC, Bibletoon commented
Ограничения сущностей в бд через конфигурацию не работает с InMemoryDb, так что нужно сделать #12 чтобы она заработала

2021-11-26 23:08 UTC, merged